#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-squidguard-update event
#--------------------------------------------------

my $event = "nethserver-squidguard-update";

event_actions($event, 'initialize-default-databases' => '00',
                      'nethserver-squidguard-conf' => '20'
);
templates2events("/etc/squid/squid.conf",  $event);
templates2events("/etc/squid/squidGuard.conf",  $event);
templates2events("/etc/squid/blacklists",  $event);
templates2events("/etc/logrotate.d/squidGuard",  $event);
event_services($event, 'squid' => 'reload');

#--------------------------------------------------
# actions for nethserver-squid-save event
#--------------------------------------------------

$event = "nethserver-squidguard-save";

event_actions($event, 'nethserver-squidguard-update-custom-list' => 20);
templates2events("/etc/squid/squid.conf",  $event);
templates2events("/etc/squid/squidGuard.conf",  $event);
event_services($event, 'squid' => 'reload');


#--------------------------------------------------
# actions for nethserver-squid-downloadlists event
#--------------------------------------------------

$event = "nethserver-squidguard-downloadlists";
event_actions($event, 'nethserver-squidguard-download' => 20);
event_actions($event, 'nethserver-squidguard-update-custom-list' => 30);
templates2events("/etc/squid/blacklists",  $event);
templates2events("/etc/squid/squidGuard.conf",  $event);
event_services($event, 'squid' => 'reload');

#--------------------------------------------------
# actions for group-modify event
#--------------------------------------------------

$event = "group-modify";
templates2events("/etc/squid/squidGuard.conf",  $event);
event_services($event, 'squid' => 'reload');
