#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-squidguard-update event
#--------------------------------------------------

my $event = "nethserver-squidguard-update";

event_actions($event, 'initialize-default-databases' => '00');
templates2events("/etc/squid/squid.conf",  $event);
templates2events("/etc/ufdbguard/ufdbGuard.conf",  $event);
templates2events("/etc/squid/blacklists",  $event);
templates2events("/etc/logrotate.d/ufdbGuard",  $event);
templates2events("/etc/logrotate.d/squidGuard",  $event);
event_services($event, 'squid' => 'reload');
event_services($event, 'ufdbGuard' => 'restart');

#--------------------------------------------------
# actions for nethserver-squidguard-save event
#--------------------------------------------------

$event = "nethserver-squidguard-save";

event_actions($event, 'nethserver-squidguard-update-custom-list' => 02);
templates2events("/etc/squid/squid.conf",  $event);
templates2events("/etc/ufdbguard/ufdbGuard.conf",  $event);
event_services($event, 'squid' => 'reload');
event_services($event, 'ufdbGuard' => 'restart');


#--------------------------------------------------
# actions for nethserver-squidguard-downloadlists event
#--------------------------------------------------

$event = "nethserver-squidguard-downloadlists";
event_actions($event, 'nethserver-squidguard-update-custom-list' => 02);
event_actions($event, 'nethserver-squidguard-download' => 30);
templates2events("/etc/squid/blacklists",  $event);
templates2events("/etc/ufdbguard/ufdbGuard.conf",  $event);
event_services($event, 'ufdbGuard' => 'reload');

#--------------------------------------------------
# actions for group-modify event
#--------------------------------------------------

$event = "group-modify";
templates2events("/etc/ufdbguard/ufdbGuard.conf",  $event);
event_services($event, 'ufdbGuard' => 'reload');

#--------------------------------------------------
# actions for firewall-objects-modify event
#--------------------------------------------------

$event = "firewall-objects-modify";
templates2events("/etc/ufdbguard/ufdbGuard.conf",  $event);
event_services($event, 'ufdbGuard' => 'reload');

#--------------------------------------------------
# actions for firewall-adjust event
#--------------------------------------------------

$event = "firewall-adjust";
templates2events("/etc/ufdbguard/ufdbGuard.conf",  $event);
event_services($event, 'ufdbGuard' => 'reload');


#--------------------------------------------------
# actions for interface-update event
#--------------------------------------------------

$event = "interface-update";
templates2events("/etc/ufdbguard/ufdbGuard.conf",  $event);

#--------------------------------------------------
# actions for squidguard-obj-delete validator
#--------------------------------------------------

validator_actions('squidguard-obj-delete', qw(
                  squidguard-referenced 20
                  ));
