#!/usr/bin/perl
#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see .
#

use esmith::ConfigDB;
my $DB = esmith::ConfigDB->open();
my $event = shift;

#
# reflect squidguard status into ufdb service
#

my $status = $DB->get_prop('squidguard', 'status') || 'disabled';
$DB->set_prop('ufdb', 'status', $status);
exit 0
