#!/bin/bash

for d in `find /var/squidGuard/blacklists/custom -type d`
do
    for f in domains urls expressions
    do
        echo /sbin/e-smith/expand-template $d/$f
        /sbin/e-smith/expand-template $d/$f 2>/dev/null
        if [ -f $d/$f ]; then
            echo /usr/bin/squidGuard -P -d -C $d/$f
            /bin/chown squid:squid $d/$f.db
        fi
    done
done
