#!/usr/bin/perl

#
# Copyright (C) 2015 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see .
#

#
# Check if a filter or time object is used inside a profile.
#

use strict;
use esmith::ConfigDB;

my $type = shift;
my $key = shift;


my $db = esmith::ConfigDB->open_ro('contentfilter');

if ($type eq 'filter') {
    foreach ($db->get_all_by_prop('type' => 'profile')) {
        my $filter = $_->prop('Filter') || '';
        $filter =~ s/filter;//g;
        if ($filter eq $key) {
            print "$key is used by " . $_->key . " profile \n";
            exit(3);
        }
    }
}

if ($type eq 'time') {
    foreach ($db->get_all_by_prop('type' => 'profile')) {
        my $time = $_->prop('Time') || '';
        $time =~ s/time;//g;
        if ($time eq $key) {
            print "$key is used by " . $_->key . " profile \n";
            exit(3);
        }
    }
}


exit(0);
